"""empty message

Revision ID: 915738a8e39a
Revises: cba685476cdd
Create Date: 2024-02-26 17:49:56.234545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915738a8e39a'
down_revision = 'cba685476cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
